### PR TITLE
Start kaborg

### LINKED ISSUE #3: Properly Executing Assignment
Properly following the assignment instructions (and also putting favorite food files into the repository).

### PR DESCRIPTION
**Pull request by KuraideWolfie**
+ Append a file with a couple of favorite foods in it.

Closes #3

### CODE REVIEW

**Comment by KuraideWolfie** [comment]
@NavidK0 Please review.

**Comment by NavidK0** [comment]
NO LETTUCE DUDE

**Comment by KuraideWolfie** [comment]
> NO LETTUCE DUDE

There was never any lettuce to begin with.

**Comment by NavidK0** [comment]
My bad, my eyesight appears to be going a bit. I read bacon as lettuce for some reason. But in actuality, what is a lettuce? Is bacon just lettuce, but made with meat? What is meat? In a philosophical sense?

**Pull request merged**
